fix

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -17,7 +17,173 @@ on:
 jobs:
   # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
+    # The type of runner that tname: Images 
+run-name: "Building images 🚀"
+on: [push]
+jobs:          
+    build-job:
+      name: Build
+      runs-on: ubuntu-latest
+      strategy:
+        fail-fast: false
+        matrix:
+          cfg:
+            - { model: "gt-be98",          sdk: "src-rt-5.04behnd.4916",      ui: "default",  skip: false }
+            - { model: "gt-be98",          sdk: "src-rt-5.04behnd.4916",      ui: "rog",      skip: false }
+      if: "!contains(github.event.commits[0].message, '[SKIP_CI]')"
+      container:
+        image: gnuton/asuswrt-merlin-toolchains-docker:latest
+        env:
+          MERLINUPDATE: "y"
+          MODEL: ${{ matrix.cfg.model }}
+          SDK: ${{ matrix.cfg.sdk }}
+          UI: ${{ matrix.cfg.ui }}
+          SKIP_BUILD: ${{ matrix.cfg.skip }}
+          GIT_REPO: "https://github.com/gnuton/asuswrt-merlin.ng.git"
+          PROJECT_DIR: "/project/asuswrt-merlin.ng"
+          ARTIFACTS_DIR: "/project/artifacts"
+          CHANGELOG_FILE: "/tmp/CHANGELOG"
+          PROJECTBASEDIR: "/project" # REMOVE_ME: Fixes https://github.com/SonarSource/sonarcloud-github-action/pull/58
+        options: --user docker 
+        volumes:
+          - /mnt:/project # HACK: Use /mnt partition since bigger than others. This prevents to run out of space
+      steps:
+        - name: Run debug commands - post
+          run: |
+            cd /
+            echo "--- Disk available ----"
+            df -h
+        - name: Fix permissions in docker image
+          if: matrix.cfg.skip == false
+          run: |
+            sudo chown -R docker:docker /github/home /home/docker /project
+        - name: "Fetch code"
+          if: matrix.cfg.skip == false
+          run: |
+            cd /project
+            if [[ $GITHUB_REF_TYPE == "tag" ]]; then
+                export TAG="${GITHUB_REF#refs/tags/}"
+                echo "Fetching code from tag $TAG"
+            else
+                export BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+                echo "Fetching code from branch $BRANCH"
+            fi
+
+            if git clone --depth 1 --branch "${TAG:-$BRANCH}" "$GIT_REPO"; then
+                echo "Code fetched successfully."
+            else
+                echo "Failed to fetch code. Check the repository and settings."
+                exit 1
+            fi
+
+            ls /home/docker
+        - name: "Set version"
+          if: matrix.cfg.skip == false
+        
+        - name: "Build"
+          if: matrix.cfg.skip == false
+          run: |
+            # #### Just for testing ####
+            mkdir -p "${PROJECT_DIR}/release/${SDK}/image/"
+            echo "TEST" > "${PROJECT_DIR}/release/${SDK}/image/${MODEL}_${UI}_puresqubi.w"
+            
+        - name: "Prepare artifacts"
+          if: matrix.cfg.skip == false
+          run: |
+            mkdir -p "${ARTIFACTS_DIR}"
+            export IMAGE_PATH=${PROJECT_DIR}/release/${SDK}/image/
+            echo "Removing images with boot loader."
+            rm -rf ${IMAGE_PATH}/*cferom*
+
+            files=("${IMAGE_PATH}"/*squashfs.pkgtb "${IMAGE_PATH}"/*.w)
+
+            if [ ${#files[@]} -gt 0 ]; then
+                for f in "${files[@]}"; do
+                    if [ -f "$f" ] && [ "${f##*.}" != "md5" ]; then
+                        echo "Creating MD5 signature for $f"
+                        md5sum "$f" > "$f.md5"
+                        echo "Copying image $f to workspace"
+                        cp "$f" "${ARTIFACTS_DIR}"
+                        cp "$f.md5" "${ARTIFACTS_DIR}"
+                    fi
+                done
+            else
+                echo "No *.squashfs.pkgtb or *.w files found in ${IMAGE_PATH}"
+            fi
+            
+            # Changelogs are the same for each models since we are building from the same branch. We do use only the one generated by GT-BE98 for now.
+            if [[ "${MODEL}" == "gt-be98" ]]; then
+              if [ -e "${CHANGELOG_FILE}" ]; then
+                cp "${CHANGELOG_FILE}" "${ARTIFACTS_DIR}"
+              fi
+            fi
+        - name: "Archive artifacts"
+          if: matrix.cfg.skip == false
+          uses: actions/upload-artifact@v4
+          with:
+            name: release-${{ matrix.cfg.model }}-${{ matrix.cfg.ui }}
+            path: "/project/artifacts"
+        - name: Download packages
+          uses: actions/download-artifact@v4
+
+    release-job:
+      name: Publish
+      needs: build-job
+      runs-on: ubuntu-latest
+      if: startsWith(github.event.ref, 'refs/tags/')
+      steps:
+        - name: Download packages
+          uses: actions/download-artifact@v2
+        - name: Get release version
+          run: |
+            echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+            echo "prerelease=$( [[ ${GITHUB_REF#refs/*/} == *alpha* || ${GITHUB_REF#refs/*/} == *beta* ]] && echo True || echo False )" >> $GITHUB_ENV
+        - name: Publish archives and packages
+          uses: softprops/action-gh-release@v1
+          with:
+            tag_name: ${{ env.version }}
+            body_path: /home/runner/work/asuswrt-merlin.ng/asuswrt-merlin.ng/release-gt-be98-default/CHANGELOG
+            draft: true
+            prerelease: ${{ env.prerelease }}
+            files: /home/runner/work/asuswrt-merlin.ng/asuswrt-merlin.ng/release*/*
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    
+    
+    manifest-job:
+      name: Publish Manifest
+      needs: build-job
+      runs-on: ubuntu-latest
+      if: startsWith(github.event.ref, 'refs/tags/') && !contains(github.event.ref, 'alpha') && !contains(github.event.ref, 'beta')
+      steps:
+        - uses: actions/checkout@v4
+          with:
+            ref: master
+        - name: Setup git config
+          run: |
+            # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
+            git config --global user.email "bot@gnuton.org"
+            git config --global user.name "Circle CI BOT"
+            git config --global push.default simple
+        - name: Download packages
+          uses: actions/download-artifact@v2
+        - name: "Publish Manifest"
+          env:
+            UPDATE_DIR: "updates"
+            CHANGELOG_FILE: "release-gt-be98-default/CHANGELOG"
+          run: |
+            export CIRCLE_TAG="${GITHUB_REF#refs/*/}"
+            MAJOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\1/')
+            MINOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\2/')
+            RELEASE_NOTE_FILE=$(echo "${MAJOR_VER}_${MINOR_VER}_note.txt" | sed "s/\./_/")
+            echo "Generating manifest file..."
+            echo "GT-BE98#FW${MAJOR_VER}#EXT${MINOR_VER}"    >> ${UPDATE_DIR}/manifest_3006.txt
+            cp ${CHANGELOG_FILE} ${UPDATE_DIR}/"${RELEASE_NOTE_FILE}"
+            echo "Uploading to github manifest and ${RELEASE_NOTE_FILE}"
+            git add ${UPDATE_DIR}
+            git commit -m "Updating Notes and manifest to version:${MAJOR_VER} ${MINOR_VER} [SKIP_CI]" -a
+            git push origin
+he job will run on
     runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
